### ISSUE TITLE
Delayed Gripper playback in joint_trajectory_file_playback.py

### ISSUE THREAD

**Issue by rethink-imcmahon** [RethinkRobotics/baxter_examples#45]
From [Juan in the brr-users group] (https://groups.google.com/a/rethinkrobotics.com/d/msg/brr-users/1sYDd_5hoMM/Eq8EyxyafekJ)

"I recently updated to SDK 1.1.1. just today I tested the standard record / play demo and the Baxter research robot.

I found out that the grippers open and close functionality is out of sync when the recorded motion is replayed.

That is, the gripper might close several seconds later than it should, or it might open several seconds later than it should."

**Comment by rethink-imcmahon** [comment]
In my testing, the gripper playback can be dead on, or quite far off. It depends on the initial condition: how far the arm needs to travel before the trajectory can be played back. The further the arm needs to travel, the more out of sync the playback becomes.

**Comment by rojas70** [comment]
How do we get to run this by using the play/record demo directly from Baxter's screen and not from the command line?

I have confirmed that the  joint_recorder.py/joint_trajectory_file_playback.py work fine from the command line from a workstation.

**Comment by rethink-imcmahon** [comment]
Thanks for testing this out, Juan. I'm glad to hear that it fixes the issue you discovered. Unfortunately, the only way to get this change into Demo Mode is to build it into the internal robot software, requiring a patch release of the internal robot software.

**Comment by rethink-imcmahon** [comment]
Resolved by #47
